import { z } from "zod";
import { AgreementConfig, FieldDef } from "../templates/types";
import { generateGenericCoverPage } from "../templates/coverPageGenerator";

const psaSchema = z.object({
  provider_name: z.string(),
  customer_name: z.string(),
  effective_date: z.string(),
  governing_law: z.string(),
  chosen_courts: z.string(),
  general_cap_amount: z.string(),
  increased_cap_amount: z.string(),
  increased_claims: z.string(),
  unlimited_claims: z.string(),
  additional_warranties: z.string(),
  security_policy: z.string(),
  customer_policies: z.string(),
  dpa: z.string(),
  insurance_minimums: z.string(),
  provider_covered_claims: z.string(),
  customer_covered_claims: z.string(),
  sow_term: z.string(),
  deliverables: z.string(),
  fees: z.string(),
  payment_period: z.string(),
  rejection_period: z.string(),
  resubmission_period: z.string(),
  time_of_assignment: z.string(),
  customer_obligations: z.string(),
});

const fields: FieldDef[] = [
  { key: "provider_name", label: "Provider Name", type: "text", placeholder: "e.g., ConsultCo", group: "Parties" },
  { key: "customer_name", label: "Customer Name", type: "text", placeholder: "e.g., ClientCorp", group: "Parties" },
  { key: "effective_date", label: "Effective Date", type: "date", group: "Key Terms" },
  { key: "governing_law", label: "Governing Law", type: "text", placeholder: "e.g., New York", group: "Key Terms" },
  { key: "chosen_courts", label: "Chosen Courts", type: "text", placeholder: "e.g., courts in Manhattan, NY", group: "Key Terms" },
  { key: "sow_term", label: "SOW Term", type: "text", placeholder: "e.g., 6 months from Effective Date", group: "Statement of Work" },
  { key: "deliverables", label: "Deliverables", type: "textarea", placeholder: "Description of work products", group: "Statement of Work" },
  { key: "fees", label: "Fees", type: "text", placeholder: "e.g., $50,000 fixed fee", group: "Statement of Work" },
  { key: "payment_period", label: "Payment Period", type: "text", placeholder: "e.g., Net 30 from invoice date", group: "Statement of Work" },
  { key: "rejection_period", label: "Rejection Period", type: "text", placeholder: "e.g., 10 business days", group: "Statement of Work" },
  { key: "resubmission_period", label: "Resubmission Period", type: "text", placeholder: "e.g., 15 business days", group: "Statement of Work" },
  { key: "time_of_assignment", label: "Time of Assignment", type: "text", placeholder: "e.g., Upon payment in full", group: "Statement of Work" },
  { key: "customer_obligations", label: "Customer Obligations", type: "textarea", placeholder: "e.g., Provide access to staging environment", group: "Statement of Work" },
  { key: "general_cap_amount", label: "General Cap Amount", type: "text", placeholder: "e.g., total Fees paid under the SOW", group: "Legal Terms" },
  { key: "increased_cap_amount", label: "Increased Cap Amount", type: "text", group: "Legal Terms" },
  { key: "increased_claims", label: "Increased Claims", type: "textarea", group: "Legal Terms" },
  { key: "unlimited_claims", label: "Unlimited Claims", type: "textarea", group: "Legal Terms" },
  { key: "additional_warranties", label: "Additional Warranties", type: "textarea", group: "Legal Terms" },
  { key: "security_policy", label: "Security Policy", type: "text", group: "Legal Terms" },
  { key: "customer_policies", label: "Customer Policies", type: "text", group: "Legal Terms" },
  { key: "dpa", label: "DPA", type: "text", placeholder: "Yes or No", group: "Legal Terms" },
  { key: "insurance_minimums", label: "Insurance Minimums", type: "text", group: "Legal Terms" },
  { key: "provider_covered_claims", label: "Provider Covered Claims", type: "textarea", group: "Legal Terms" },
  { key: "customer_covered_claims", label: "Customer Covered Claims", type: "textarea", group: "Legal Terms" },
];

export const psaConfig: AgreementConfig = {
  slug: "psa",
  name: "Professional Services Agreement",
  description: "Standard terms for consulting and services engagements, covering deliverables, IP, payment, and warranties.",
  coverTemplate: null,
  termsTemplate: "/templates/PSA.md",
  fields,
  schema: psaSchema,
  buildFieldMap: (values) => {
    const v = values as Record<string, string>;
    return {
      Provider: v.provider_name || "[Provider]",
      Customer: v.customer_name || "[Customer]",
      "Effective Date": v.effective_date || "[Effective Date]",
      "Governing Law": v.governing_law || "[Governing Law]",
      "Chosen Courts": v.chosen_courts || "[Chosen Courts]",
      "General Cap Amount": v.general_cap_amount || "[General Cap Amount]",
      "Increased Cap Amount": v.increased_cap_amount || "[Increased Cap Amount]",
      "Increased Claims": v.increased_claims || "[Increased Claims]",
      "Unlimited Claims": v.unlimited_claims || "[Unlimited Claims]",
      "Additional Warranties": v.additional_warranties || "None",
      "Security Policy": v.security_policy || "[Security Policy]",
      "Customer Policies": v.customer_policies || "None",
      DPA: v.dpa || "[DPA]",
      "Insurance Minimums": v.insurance_minimums || "None",
      "Provider Covered Claim": v.provider_covered_claims || "[Provider Covered Claims]",
      "Provider Covered Claims": v.provider_covered_claims || "[Provider Covered Claims]",
      "Customer Covered Claim": v.customer_covered_claims || "[Customer Covered Claims]",
      "Customer Covered Claims": v.customer_covered_claims || "[Customer Covered Claims]",
      "SOW Term": v.sow_term || "[SOW Term]",
      Deliverables: v.deliverables || "[Deliverables]",
      Fees: v.fees || "[Fees]",
      "Payment Period": v.payment_period || "[Payment Period]",
      "Rejection Period": v.rejection_period || "[Rejection Period]",
      "Resubmission Period": v.resubmission_period || "[Resubmission Period]",
      "Time of Assignment": v.time_of_assignment || "[Time of Assignment]",
      "Customer Obligations": v.customer_obligations || "None",
    };
  },
  generateCoverPage: (values) => generateGenericCoverPage("Professional Services Agreement", fields, values),
  defaultValues: {
    provider_name: "", customer_name: "", effective_date: "", governing_law: "",
    chosen_courts: "", general_cap_amount: "", increased_cap_amount: "",
    increased_claims: "", unlimited_claims: "", additional_warranties: "",
    security_policy: "", customer_policies: "", dpa: "", insurance_minimums: "",
    provider_covered_claims: "", customer_covered_claims: "", sow_term: "",
    deliverables: "", fees: "", payment_period: "", rejection_period: "",
    resubmission_period: "", time_of_assignment: "", customer_obligations: "",
  },
};
